---
- name: Ensure the build packages are present
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - cmake

- name: Ensure the working directory is deleted
  file:
    path: "{{ rtsp_camera_build_directory }}"
    state: absent

- name: Ensure the working directory exists
  file:
    path: "{{ rtsp_camera_build_directory }}"
    state: directory
    mode: 0755

- name: Ensure the v4l2 rtsp server git repo is in place
  git:
    repo: 'https://github.com/mpromonet/v4l2rtspserver'
    dest: "{{ rtsp_camera_build_directory }}"
    version: "{{ rtsp_camera_git_commit }}"
    depth: 1

- name: Cmake the server
  command:                   # noqa 301
    cmd: cmake .
  args:
    chdir: "{{ rtsp_camera_build_directory }}"

- name: Make the server
  command:                   # noqa 301
    cmd: make
  args:
    chdir: "{{ rtsp_camera_build_directory }}"

- name: Install the server
  command:                   # noqa 301
    cmd: make install
  args:
    chdir: "{{ rtsp_camera_build_directory }}"
  notify: restart v4l2rtspserver

- name: Clean up the working directory
  file:
    path: "{{ rtsp_camera_build_directory }}"
    state: absent
  when: not rtsp_camera_preserve_build_dir
