---
- name: Ensure the build packages are present
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - cmake

- name: Clean up the working directory
  file:
    path: /tmp/v4l2rtspserver
    state: absent

- name: Ensure the v4l2 rtsp server git repo is in place
  git:
    repo: 'https://github.com/mpromonet/v4l2rtspserver'
    dest: /tmp/v4l2rtspserver
    version: "{{ rtsp_camera_git_commit }}"

- name: Cmake the server
  command:                   # noqa 301
    cmd: cmake .
  args:
    chdir: /tmp/v4l2rtspserver

- name: Make the server
  command:                   # noqa 301
    cmd: make
  args:
    chdir: /tmp/v4l2rtspserver

- name: Install the server
  command:                   # noqa 301
    cmd: make install
  args:
    chdir: /tmp/v4l2rtspserver

- name: Clean up the working directory
  file:
    path: /tmp/v4l2rtspserver
    state: absent
